### PR TITLE
Add RO as glossary language

### PR DESCRIPTION
**Pull request by johnisom**
I would ask to not merge and release this change until I verify the feature is released in production

### CODE REVIEW

**Comment by JanEbbing** [comment]
LGTM

**Comment by johnisom** [comment]
Hi @JanEbbing This can be merged now :slightly_smiling_face:

**Review by seekuehe — APPROVED** [review]

**Comment by daniel-jones-dev** [comment]
As this PR increased the version number (to 2.15.0), we need to tag and make a new GitHub release too. @seekuehe can you do that?

**Comment by seekuehe** [comment]
Done

**Pull request merged**
